#!/bin/bash
set -e

# Parameters from GitHub Action
S3_KEY=$S3_KEY
TOMCAT_HOST=$TOMCAT_HOST
TOMCAT_USER="tomcat"
TOMCAT_WEBAPPS="/opt/tomcat/webapps"
PRIVATE_KEY="/var/lib/jenkins/.ssh/tomcat_id_rsa"
S3_BUCKET="insured-assurance-artifacts"
AWS_REGION="us-east-1"

# Download WAR from S3
aws s3 cp s3://$S3_BUCKET/$S3_KEY /tmp/app.war --region $AWS_REGION

# Deploy WAR to Tomcat
scp -i $PRIVATE_KEY /tmp/app.war $TOMCAT_USER@$TOMCAT_HOST:$TOMCAT_WEBAPPS/ROOT.war

# Restart Tomcat
ssh -i $PRIVATE_KEY $TOMCAT_USER@$TOMCAT_HOST "sudo systemctl restart tomcat"

echo "Deployment completed successfully!"
