name: Java CI/CD to Tomcat

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  S3_BUCKET: insured-assurance-artifacts
  JENKINS_URL: http://107.23.57.176:8080
  JENKINS_USER: admin

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build WAR
      - name: Build WAR
        run: mvn clean package

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Upload WAR to S3
      - name: Upload WAR to S3
        run: |
          aws s3 cp target/insured-assurance.war s3://${{ env.S3_BUCKET }}/insured-assurance.war

      # Trigger Jenkins job
      - name: Trigger Jenkins Deployment
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ env.JENKINS_URL }}
          user: ${{ env.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: InsuredAssuranceDeploy
          parameters: "S3_KEY=insured-assurance.war TOMCAT_HOST=100.27.214.51"
